name: Release

on:
  push:
    tags:
      - 'v*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.15.0
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        working-directory: npm/y-phoenix-channel
      - run: npm run build --if-present
        working-directory: npm/y-phoenix-channel
      - run: npm test
        working-directory: npm/y-phoenix-channel
      - run: npm publish
        working-directory: npm/y-phoenix-channel